export const FACTORY_ADDRESS = process.env.NEXT_PUBLIC_FACTORY_ADDRESS ?? "";
export const ACCESS_MANAGER_ADDRESS = process.env.NEXT_PUBLIC_ACCESS_MANAGER_ADDRESS
	?? process.env.NEXT_PUBLIC_VERIFICATION_ACCESS_MANAGER_ADDRESS
	?? "";
