"""initial_schema

Revision ID: 07f63ea8235e
Revises: 
Create Date: 2026-04-15 13:44:36.344706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07f63ea8235e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_grants',
    sa.Column('grant_id', sa.UUID(), nullable=False),
    sa.Column('student_did', sa.String(length=255), nullable=False),
    sa.Column('platform_name', sa.String(length=255), nullable=False),
    sa.Column('platform_domain', sa.String(length=255), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('grant_id')
    )
    op.create_index(op.f('ix_access_grants_student_did'), 'access_grants', ['student_did'], unique=False)
    op.create_table('auth_audit_log',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('did_attempted', sa.String(length=255), nullable=True),
    sa.Column('portal', sa.String(length=100), nullable=False),
    sa.Column('nonce_used', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('failure_check', sa.Integer(), nullable=True),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('attempted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_auth_audit_log_did_attempted'), 'auth_audit_log', ['did_attempted'], unique=False)
    op.create_table('credentials',
    sa.Column('credential_id', sa.UUID(), nullable=False),
    sa.Column('holder_did', sa.String(length=255), nullable=False),
    sa.Column('vc_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('revocation_index', sa.Integer(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('credential_id')
    )
    op.create_index(op.f('ix_credentials_holder_did'), 'credentials', ['holder_did'], unique=False)
    op.create_table('csv_records',
    sa.Column('record_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('secret_key_hash', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('is_registered', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('record_id')
    )
    op.create_table('data_update_requests',
    sa.Column('update_id', sa.UUID(), nullable=False),
    sa.Column('student_did', sa.String(length=255), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=False),
    sa.Column('new_value', sa.Text(), nullable=False),
    sa.Column('requires_vc_reissue', sa.Boolean(), nullable=False),
    sa.Column('approvals_count', sa.Integer(), nullable=False),
    sa.Column('approver_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collected_shares', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('update_id')
    )
    op.create_index(op.f('ix_data_update_requests_student_did'), 'data_update_requests', ['student_did'], unique=False)
    op.create_table('did_documents',
    sa.Column('did', sa.String(length=255), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=False),
    sa.Column('did_document', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blockchain_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('did')
    )
    op.create_table('governance_proposals',
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('proposal_type', sa.String(length=30), nullable=False),
    sa.Column('target_panelist_id', sa.UUID(), nullable=True),
    sa.Column('new_panelist_name', sa.String(length=255), nullable=True),
    sa.Column('new_panelist_email', sa.String(length=255), nullable=True),
    sa.Column('new_panelist_department', sa.String(length=100), nullable=True),
    sa.Column('proposed_by', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('votes_yes', sa.Integer(), nullable=False),
    sa.Column('votes_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('proposal_id')
    )
    op.create_table('governance_votes',
    sa.Column('vote_id', sa.UUID(), nullable=False),
    sa.Column('proposal_id', sa.UUID(), nullable=False),
    sa.Column('panelist_id', sa.UUID(), nullable=False),
    sa.Column('vote', sa.Boolean(), nullable=False),
    sa.Column('voted_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('vote_id')
    )
    op.create_index(op.f('ix_governance_votes_proposal_id'), 'governance_votes', ['proposal_id'], unique=False)
    op.create_table('metrics',
    sa.Column('metric_id', sa.UUID(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('duration_ms', sa.Float(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index(op.f('ix_metrics_operation'), 'metrics', ['operation'], unique=False)
    op.create_table('nonce_store',
    sa.Column('nonce', sa.String(length=64), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_by_did', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('nonce')
    )
    op.create_table('panelists',
    sa.Column('panelist_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('key_share_hash', sa.Text(), nullable=True),
    sa.Column('key_share_encrypted', sa.Text(), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('panelist_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('registration_requests',
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('csv_match', sa.Boolean(), nullable=False),
    sa.Column('csv_record_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approvals_count', sa.Integer(), nullable=False),
    sa.Column('rejections_count', sa.Integer(), nullable=False),
    sa.Column('approver_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collected_shares', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('request_id')
    )
    op.create_table('revocation_registry',
    sa.Column('registry_id', sa.UUID(), nullable=False),
    sa.Column('bitstring', sa.Text(), nullable=False),
    sa.Column('next_index', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('registry_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('revocation_registry')
    op.drop_table('registration_requests')
    op.drop_table('panelists')
    op.drop_table('nonce_store')
    op.drop_index(op.f('ix_metrics_operation'), table_name='metrics')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_governance_votes_proposal_id'), table_name='governance_votes')
    op.drop_table('governance_votes')
    op.drop_table('governance_proposals')
    op.drop_table('did_documents')
    op.drop_index(op.f('ix_data_update_requests_student_did'), table_name='data_update_requests')
    op.drop_table('data_update_requests')
    op.drop_table('csv_records')
    op.drop_index(op.f('ix_credentials_holder_did'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_auth_audit_log_did_attempted'), table_name='auth_audit_log')
    op.drop_table('auth_audit_log')
    op.drop_index(op.f('ix_access_grants_student_did'), table_name='access_grants')
    op.drop_table('access_grants')
    # ### end Alembic commands ###
