"""add_eth_address_to_panelists

Revision ID: 47d64f7bd053
Revises: aa2520fc1c68
Create Date: 2026-04-16 19:08:23.175793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47d64f7bd053'
down_revision: Union[str, None] = 'aa2520fc1c68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panelists', sa.Column('eth_address', sa.String(length=42), nullable=True))
    op.create_unique_constraint(None, 'panelists', ['eth_address'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'panelists', type_='unique')
    op.drop_column('panelists', 'eth_address')
    # ### end Alembic commands ###
