"""v4_add_encrypted_vc_and_vc_cid

Revision ID: aa2520fc1c68
Revises: cc8cbf069bf5
Create Date: 2026-04-15 23:01:54.528688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa2520fc1c68'
down_revision: Union[str, None] = 'cc8cbf069bf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('encrypted_vc', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('credentials', sa.Column('vc_cid', sa.String(length=255), nullable=True))
    op.alter_column('credentials', 'vc_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('credentials', 'vc_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('credentials', 'vc_cid')
    op.drop_column('credentials', 'encrypted_vc')
    # ### end Alembic commands ###
