"""add_institution_keys_table

Revision ID: aa3ab56fec96
Revises: 07f63ea8235e
Create Date: 2026-04-15 14:04:56.234372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa3ab56fec96'
down_revision: Union[str, None] = '07f63ea8235e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_keys',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('public_key_pem', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('institution_keys')
    # ### end Alembic commands ###
