"""add_is_anomaly_to_audit_log

Revision ID: cc8cbf069bf5
Revises: dbbaf3b0ff45
Create Date: 2026-04-15 18:30:37.261523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8cbf069bf5'
down_revision: Union[str, None] = 'dbbaf3b0ff45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_audit_log', sa.Column('is_anomaly', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_audit_log', 'is_anomaly')
    # ### end Alembic commands ###
