"""add_revocation_fields_to_credentials

Revision ID: dbbaf3b0ff45
Revises: aa3ab56fec96
Create Date: 2026-04-15 14:21:02.182871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbbaf3b0ff45'
down_revision: Union[str, None] = 'aa3ab56fec96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('credentials', sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('credentials', sa.Column('revocation_reason', sa.Text(), nullable=True))
    op.add_column('credentials', sa.Column('revocation_approvers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('credentials', 'revocation_approvers')
    op.drop_column('credentials', 'revocation_reason')
    op.drop_column('credentials', 'revoked_at')
    # ### end Alembic commands ###
